export const UPDATE_COMMENTS = 'UPDATE_COMMENTS';
export const ASYNC_ADD_COMMENT = 'ASYNC_ADD_COMMENT';
export const CHANGE_COMMENT_TEXT = 'CHANGE_COMMENT_TEXT';
export const CHANGE_IS_COMMENT_ACTIVE = 'CHANGE_IS_COMMENT_ACTIVE';