export const ASYNC_PUSH_VIDEO = 'ASYNC_PUSH_VIDEO';
export const ASYNC_REMOVE_VIDEO = 'ASYNC_REMOVE_VIDEO';
export const ASYNC_POST_PLAYING_VIDEO_FROM_QUE = 'ASYNC_POST_PLAYING_VIDEO_FROM_QUE';
export const ASYNC_UPDATE_QUE = 'ASYNC_UPDATE_QUE';

export const SET_SEARCH_RESULT  = 'SET_SEARCH_RESULT';
export const UPDATE_QUE = 'UPDATE_QUE';